
# Note: These are dummy values and should be replaced with actual API keys and URLs.

# APIs endpoints
TOGETHER_API_BASE: http://*****************.********.****/*********/********


# API keys

TAVILY_API_KEY: ***********************************************************************************************************************************************************************************
TOGETHER_API_KEY: ***********************************************************************************************************************************************************************************
#https://api.together.xyz/settings/api-keys
WOLFRAM_ALPHA_KEY: ***********************************************************************************************************************************************************************************

