#env file deleting personal/sensitive data. These are the variables in the Jupyter Lab environment provided in the short course 'Introducing Multimodal Llama 3.2' from deeplearning.ai
#todo: check whats each parameter used for inside Jupyter Lab

#AWS_CONTAINER_CREDENTIALS_RELATIVE_URI:
#AWS_EXECUTION_ENV:
CLICOLOR: '1'
CLICOLOR_FORCE: '1'
#COURSE_ID:
DLAI_LLAMA_STACK_API_TOGETHER_URL: http://jupyter-api-proxy.internal.dlai/rev-proxy/llamastack_together
#DLAI_LOCAL_URL:
DLAI_TAVILY_BASE_URL: http://jupyter-api-proxy.internal.dlai/rev-proxy/tavily_search
DLAI_TOGETHER_API_BASE: http://jupyter-api-proxy.internal.dlai/rev-proxy/together
DLAI_WOLFRAM_ALPHA_BASE_URL: http://jupyter-api-proxy.internal.dlai/rev-proxy/wolframalpha
ECS_AGENT_URI: http://169.254.170.2/api/87c336bf-bdec-4100-ad46-eb2405d67207
ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3/87c336bf-bdec-4100-ad46-eb2405d67207
ECS_CONTAINER_METADATA_URI_V4: http://169.254.170.2/v4/87c336bf-bdec-4100-ad46-eb2405d67207
FORCE_COLOR: '1'
GIT_PAGER: cat
#GPG_KEY:
#HOME: /home/jovyan home directory typically found in JupyterNotebook environments, specifically in cloud-based or containerized setups. It's a non-root user
#HOSTNAME:
JPY_PARENT_PID: '7'
JUPYTER_TOKEN: I2RwD0TNUc7H_4Y0qaQeMZuC-m7R1CcErfSGopiyX17rVVQZ7A1Arwz2UTygMVnq
LANG: C.UTF-8
#LESSON_ID:
MPLBACKEND: module://matplotlib_inline.backend_inline
PAGER: cat
#PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PORT1: '7860'
PWD: /
PYDEVD_USE_FRAME_EVAL: 'NO'
PYTHON_GET_PIP_SHA256: dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9
PYTHON_GET_PIP_URL: https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py
PYTHON_PIP_VERSION: '24.0'
PYTHON_SETUPTOOLS_VERSION: 65.5.1
PYTHON_VERSION: 3.11.9
#REV_PROXY_BASE_DOMAIN:
SHLVL: '0'
#TAVILY_API_KEY:
TERM: xterm-color
TOGETHER_API_KEY:
WOLFRAM_ALPHA_KEY:
_: /usr/local/bin/jupyter
